# https://www.jpx.co.jp/markets/statistics-equities/misc/04.html
# 2025年9月
- 種別: "水産・農林業"
  単純_PER_倍: 10.8
  単純_PBR_倍: 0.9
  加重_PER_倍: 11.7
  加重_PBR_倍: 1.0
- 種別: "鉱業"
  単純_PER_倍: 9.4
  単純_PBR_倍: 0.8
  加重_PER_倍: 7.6
  加重_PBR_倍: 0.7
- 種別: "建設業"
  単純_PER_倍: 15.3
  単純_PBR_倍: 1.4
  加重_PER_倍: 14.5
  加重_PBR_倍: 1.4
- 種別: "食料品"
  単純_PER_倍: 19.9
  単純_PBR_倍: 1.2
  加重_PER_倍: 26.0
  加重_PBR_倍: 1.7
- 種別: "繊維製品"
  単純_PER_倍: 19.3
  単純_PBR_倍: 1.1
  加重_PER_倍: 18.5
  加重_PBR_倍: 1.0
- 種別: "パルプ・紙"
  単純_PER_倍: 13.8
  単純_PBR_倍: 0.5
  加重_PER_倍: 16.9
  加重_PBR_倍: 0.6
- 種別: "化学"
  単純_PER_倍: 16.8
  単純_PBR_倍: 1.1
  加重_PER_倍: 18.2
  加重_PBR_倍: 1.4
- 種別: "医薬品"
  単純_PER_倍: 17.3
  単純_PBR_倍: 1.3
  加重_PER_倍: 23.1
  加重_PBR_倍: 1.9
- 種別: "石油・石炭製品"
  単純_PER_倍: 16.0
  単純_PBR_倍: 0.8
  加重_PER_倍: 12.3
  加重_PBR_倍: 0.8
- 種別: "ゴム製品"
  単純_PER_倍: 12.6
  単純_PBR_倍: 1.0
  加重_PER_倍: 15.0
  加重_PBR_倍: 1.2
- 種別: "ガラス・土石製品"
  単純_PER_倍: 20.9
  単純_PBR_倍: 1.4
  加重_PER_倍: 34.3
  加重_PBR_倍: 1.0
- 種別: "鉄鋼"
  単純_PER_倍: 9.7
  単純_PBR_倍: 0.7
  加重_PER_倍: 10.0
  加重_PBR_倍: 0.6
- 種別: "非鉄金属"
  単純_PER_倍: 16.1
  単純_PBR_倍: 1.2
  加重_PER_倍: 22.5
  加重_PBR_倍: 1.6
- 種別: "金属製品"
  単純_PER_倍: 12.3
  単純_PBR_倍: 0.8
  加重_PER_倍: 16.7
  加重_PBR_倍: 1.0
- 種別: "機械"
  単純_PER_倍: 18.8
  単純_PBR_倍: 1.5
  加重_PER_倍: 21.2
  加重_PBR_倍: 1.9
- 種別: "電気機器"
  単純_PER_倍: 19.4
  単純_PBR_倍: 1.7
  加重_PER_倍: 24.9
  加重_PBR_倍: 2.4
- 種別: "輸送用機器"
  単純_PER_倍: 17.1
  単純_PBR_倍: 1.0
  加重_PER_倍: 12.1
  加重_PBR_倍: 1.0
- 種別: "精密機器"
  単純_PER_倍: 21.1
  単純_PBR_倍: 1.8
  加重_PER_倍: 26.7
  加重_PBR_倍: 2.8
- 種別: "その他製品"
  単純_PER_倍: 18.6
  単純_PBR_倍: 1.4
  加重_PER_倍: 31.9
  加重_PBR_倍: 3.1
- 種別: "電気・ガス業"
  単純_PER_倍: 8.6
  単純_PBR_倍: 0.7
  加重_PER_倍: 7.1
  加重_PBR_倍: 0.7
- 種別: "陸運業"
  単純_PER_倍: 13.4
  単純_PBR_倍: 1.1
  加重_PER_倍: 12.9
  加重_PBR_倍: 1.2
- 種別: "海運業"
  単純_PER_倍: 4.8
  単純_PBR_倍: 0.7
  加重_PER_倍: 4.4
  加重_PBR_倍: 0.7
- 種別: "空運業"
  単純_PER_倍: 10.4
  単純_PBR_倍: 1.2
  加重_PER_倍: 10.3
  加重_PBR_倍: 1.2
- 種別: "倉庫・運輸関連業"
  単純_PER_倍: 17.9
  単純_PBR_倍: 1.2
  加重_PER_倍: 16.7
  加重_PBR_倍: 1.2
- 種別: "情報・通信業"
  単純_PER_倍: 25.7
  単純_PBR_倍: 2.5
  加重_PER_倍: 21.8
  加重_PBR_倍: 2.1
- 種別: "卸売業"
  単純_PER_倍: 12.7
  単純_PBR_倍: 1.2
  加重_PER_倍: 13.2
  加重_PBR_倍: 1.5
- 種別: "小売業"
  単純_PER_倍: 22.1
  単純_PBR_倍: 1.9
  加重_PER_倍: 29.1
  加重_PBR_倍: 2.4
- 種別: "銀行業"
  単純_PER_倍: 12.1
  単純_PBR_倍: 0.6
  加重_PER_倍: 14.7
  加重_PBR_倍: 1.0
- 種別: "証券、商品先物取引業"
  単純_PER_倍: 13.6
  単純_PBR_倍: 1.2
  加重_PER_倍: 12.0
  加重_PBR_倍: 1.1
- 種別: "保険業"
  単純_PER_倍: 12.3
  単純_PBR_倍: 1.3
  加重_PER_倍: 10.6
  加重_PBR_倍: 1.5
- 種別: "その他金融業"
  単純_PER_倍: 12.7
  単純_PBR_倍: 1.0
  加重_PER_倍: 13.5
  加重_PBR_倍: 1.1
- 種別: "不動産業"
  単純_PER_倍: 13.7
  単純_PBR_倍: 1.7
  加重_PER_倍: 15.1
  加重_PBR_倍: 1.4
- 種別: "サービス業"
  単純_PER_倍: 20.0
  単純_PBR_倍: 2.0
  加重_PER_倍: 31.7
  加重_PBR_倍: 1.6
